name: Deploy to Xserver

on:
  push:
    branches:
      - main  # `main` ブランチに push されたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # GitHubリポジトリのルートディレクトリ
          server-dir: /public_html/  # Xserverの公開ディレクトリ
